name: CI
on:
  push:
jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
    - env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VAULT_CLI_VERSION: "1.10.4"
        TERRAFORM_VERSION: "1.2.2"
        VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
        VAULT_ROLE_ID: ${{ secrets.VAULT_ROLE_ID }}
        VAULT_SECRET_ID: ${{ secrets.VAULT_SECRET_ID }}
      run: |
        curl -s https://raw.githubusercontent.com/OriHoch/uumpa-ci-toolbox/65a0704332e63d51f63981dbb25cd83682dc4078/bin/github_actions_install.sh \
          | bash -s 4ed9d7055f0aa9629de1291fe0f42e154709b0b6 OriHoch/uumpa-ci-toolbox &&\
        uci github actions self-checkout --config-user-name "hasadna-iac-ci" &&\
        uci vault install --version $VAULT_CLI_VERSION &&\
        uci terraform install --version $TERRAFORM_VERSION &&\
        export VAULT_TOKEN="$(uci vault approle-login $VAULT_ROLE_ID $VAULT_SECRET_ID)" &&\
        terraform init "-backend-config=$(bin/get_backend_config.py)" &&\
        eval "$(bin/get_secret_envvars.py)" &&\
        terraform plan -input=false -lock=false
